name: my first action

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "my first action"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md
